jekyll: false
name: Update G2B Dashboard

on:
  schedule:
    - cron: '...'
  workflow_dispatch:

# --- 여기 아래 2줄을 추가하세요 ---
permissions:
  contents: write
# -----------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    ...
